const ADD_COLUMN = "ADD_COLUMN";
const EDIT_COLUMN = "EDIT_COLUMN";
const REMOVE_COLUMN = "REMOVE_COLUMN";
const ADD_CARD = "ADD_CARD";
const EDIT_CARD = "EDIT_CARD";
const REMOVE_CARD = "REMOVE_CARD";
const MOVE_CARD = "MOVE_CARD";
const SET_SELECTED_CARD = "SET_SELECTED_CARD";

export {
  ADD_COLUMN,
  EDIT_COLUMN,
  REMOVE_COLUMN,
  ADD_CARD,
  EDIT_CARD,
  REMOVE_CARD,
  MOVE_CARD,
  SET_SELECTED_CARD,
};
